# -*- coding: utf-8 -*-
"""TSF-TASK-2-YAMINI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yL2rT-zIV1ItS9TymSu458CqwTslMDzB

# **Prediction using Unsupervised ML**
# **Yamini Chalapaka**
# **Task-2**

**Importing Libraries**
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets

"""**Loading datasets**"""

iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df.head()

"""**Exploring the dataset**"""

iris_df.tail()

iris_df.shape

iris_df.info()

iris_df.isnull()

"""**Finding number of clusters for K Means classification**"""

X = iris_df.iloc[:, [0, 1, 2, 3]].values

from sklearn.cluster import KMeans
wcss = []

for i in range(1, 11):
  kmeans = KMeans(n_clusters = i, init = 'k-means++',
                  max_iter = 300, n_init = 10, random_state = 0)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

"""**Plotting the results onto a line graph**"""

#Elbow method
plt.plot(range(1, 11), wcss)
plt.title('The Elbow method')
plt.xlabel('Number of cluster')
plt.ylabel('WCSS') #Within cluster sum of squares
plt.grid(color = 'grey')
plt.show()

"""**KMeans classifier**"""

#Number of clusters = 3
kmeans = KMeans(n_clusters = 3, init = 'k-means++',
                max_iter = 200, n_init = 10, random_state = 0)
y_kmeans = kmeans.fit_predict(X)

"""**Plotting clusters on Graph**"""

plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1],
            s = 100, c = 'yellow', label = 'Iris-setosa')
plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1],
            s = 100, c = 'blue', label = 'Iris-versicolour')
plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1],
            s = 100, c = 'purple', label = 'Iris-virginica')

#Plotting centroids
plt.scatter(kmeans.cluster_centers_[:, 0],  kmeans.cluster_centers_[:, 1],
            s = 100, c = 'red', label = 'centroids')

plt.grid(color = 'grey')
plt.legend()

"""**Thus, we can depict the observations. It is clear that there are 3 clusters from the visualizaton**"""